# PlayerDeadManager 配置文件
# PlayerDeadManager Configuration File
# 作者: saga
# Author: saga
# 版本: 1.0.0
# Version: 1.0.0

# 语言设置
# Language Settings
language:
  # 语言代码 (zh: 中文, en: 英文)
  # Language code (zh: Chinese, en: English)
  code: "en"

# 墓碑设置
# Tombstone Settings
tombstone:
  # 墓碑方块类型 (支持Oraxen自定义方块)
  # Tombstone block type (supports Oraxen custom blocks)
  block-type: "PLAYER_HEAD"
  # 自定义模型数据 (用于Oraxen等插件)
  # Custom model data (for Oraxen and other plugins)
  custom-model-data: 0
  # 墓碑保护时间 (分钟)
  # Tombstone protection time (minutes)
  protection-time: 60
  # 墓碑消失时间 (小时)
  # Tombstone despawn time (hours)
  despawn-time: 24
  # 最大墓碑数量限制
  # Maximum tombstone limit
  max-tombstones: 3
  # 自动清理间隔 (小时)
  # Auto cleanup interval (hours)
  cleanup-interval: 1
  # 是否只在PVP死亡时创建墓碑
  # Only create tombstone on PVP death
  pvp-only: true
  # 头颅完全保护 (永远不被破坏，只有过期或取完物品才移除)
  # Complete skull protection (never destroyed, only removed when expired or items taken)
  skull-protection: true

# 保存图腾设置
# Save Totem Settings
totem:
  # 是否启用保存图腾功能
  # Enable save totem feature
  enabled: true
  # 图腾物品类型
  # Totem item type
  item-type: "TOTEM_OF_UNDYING"
  # 图腾显示名称
  # Totem display name
  display-name: "&6保存图腾"
  # 图腾描述
  # Totem lore
  lore:
    - "&7死亡时消耗1个图腾"
    - "&7可以保护你的物品和经验"
    - "&a右键使用"
  # 自定义模型数据
  # Custom model data
  custom-model-data: 0

# 传送GUI设置
# Teleport GUI Settings
teleport-gui:
  # GUI标题
  # GUI title
  title: "&8死亡地点传送"
  # GUI大小 (9的倍数)
  # GUI size (multiple of 9)
  size: 27
  # 传送费用 (需要Vault插件)
  # Teleport cost (requires Vault plugin)
  cost: 100.0
  # 是否启用传送费用
  # Enable teleport cost
  cost-enabled: false

# 全息图设置
# Hologram Settings
hologram:
  # 是否启用全息图
  # Enable hologram
  enabled: true
  # 全息图高度偏移
  # Hologram height offset
  height-offset: 1.5
  # 全息图内容格式
  # Hologram content format
  format:
    - "&6墓碑"
    - "&7所有者: &f{player}"
    - "&7死亡时间: &f{time}"
    - "&7保护剩余: &f{protection}"
  # 更新间隔 (秒)
  # Update interval (seconds)
  update-interval: 1

# 粒子效果设置
# Particle Effects Settings
particles:
  # 是否启用粒子效果
  # Enable particle effects
  enabled: true
  # 粒子类型
  # Particle type
  type: "SOUL"
  # 粒子数量
  # Particle count
  count: 5
  # 粒子范围
  # Particle range
  range: 0.5
  # 粒子生成间隔 (tick)
  # Particle spawn interval (ticks)
  interval: 20

# 通知设置
# Notification Settings
notifications:
  # 是否启用拾取通知
  # Enable looting notification
  looting-notification: true
  # 是否启用视觉引导
  # Enable visual guidance
  visual-guidance: true
  # 引导范围 (方块)
  # Guidance range (blocks)
  guidance-range: 50

# 经验设置
# Experience Settings
experience:
  # 其他玩家拾取时获得的经验比例
  # Experience ratio when other players loot
  public-access-ratio: 0.5
  # 是否保留经验等级
  # Keep experience level
  keep-level: false

# 经济设置
# Economy Settings
economy:
  # 是否启用死亡扣费保险机制
  # Enable death cost insurance mechanism
  enabled: true
  # 死亡扣费金额 (扣费成功=保住物品不掉落，扣费失败=正常掉落+生成墓碑)
  # Death cost amount (success=keep items, fail=normal drop+create tombstone)
  cost: 1.0

# 数据库设置
# Database Settings
database:
  # 数据库文件名
  # Database filename
  filename: "tombstones.db"
  # 连接池大小
  # Connection pool size
  pool-size: 5
  # 连接超时 (秒)
  # Connection timeout (seconds)
  timeout: 30

# 世界设置
# World Settings
worlds:
  # 启用的世界列表 (空列表表示所有世界)
  # Enabled worlds list (empty list means all worlds)
  enabled-worlds: []
  # 禁用的世界列表
  # Disabled worlds list
  disabled-worlds:
    - "world_nether"
    - "world_the_end"
  # 世界特定配置
  # World-specific configurations
  world-configs:
    # 示例：为特定世界设置不同的配置
    # Example: Different settings for specific worlds
    "world":
      pvp-only: true
      economy-enabled: true
      skull-protection: true
    "world_pvp":
      pvp-only: false
      economy-enabled: false
      skull-protection: false

# 权限设置
# Permission Settings
permissions:
  # 是否启用权限检查
  # Enable permission check
  enabled: true
  # 基础权限节点
  # Base permission node
  base: "playerdeadmanager.use"
  # 管理员权限节点
  # Admin permission node
  admin: "playerdeadmanager.admin"
  # 功能特定权限
  # Feature-specific permissions
  features:
    # PVP死亡墓碑权限
    # PVP death tombstone permission
    pvp-tombstone: "playerdeadmanager.pvp"
    # 经济系统权限
    # Economy system permission
    economy: "playerdeadmanager.economy"
    # 头颅保护权限
    # Skull protection permission
    skull-protection: "playerdeadmanager.protection"
    # 绕过世界限制权限
    # Bypass world restrictions permission
    bypass-world: "playerdeadmanager.bypass.world"

# VIP权限时间设置
# VIP Permission Time Settings
vip-times:
  # 是否启用VIP权限时间
  # Enable VIP permission time
  enabled: true
  # VIP权限配置 (权限节点: {保护时间(分钟), 消失时间(小时)})
  # VIP permission configuration (permission: {protection-time(minutes), despawn-time(hours)})
  permissions:
    "playerdeadmanager.vip1":
      protection-time: 120
      despawn-time: 48
    "playerdeadmanager.vip2":
      protection-time: 180
      despawn-time: 72
    "playerdeadmanager.vip3":
      protection-time: 240
      despawn-time: 96

# VIP豁免设置
# VIP Exemption Settings
vip-exemption:
  # 是否启用VIP豁免功能
  # Enable VIP exemption feature
  enabled: true
  # 豁免记录清理天数 (删除多少天前的记录)
  # Days to keep exemption records (delete records older than this)
  cleanup-days: 7

# 兼容性设置
# Compatibility Settings
compatibility:
  # Vault经济插件支持
  # Vault economy plugin support
  vault: true
  # WorldGuard区域保护支持
  # WorldGuard region protection support
  worldguard: false
  # GriefPrevention保护支持
  # GriefPrevention protection support
  griefprevention: false
